# Generated by Django 6.1 on 2026-08-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacity', '0003_remove_workcenter_headcount_and_more'),
        ('planning', '0003_itkrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Hesablanır'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Xəta')], default='RUNNING', max_length=20, verbose_name='Status')),
                ('total_operations', models.PositiveIntegerField(default=0, verbose_name='Ümumi operation')),
                ('scheduled_operations', models.PositiveIntegerField(default=0, verbose_name='Proqrama alınan')),
                ('not_scheduled_operations', models.PositiveIntegerField(default=0, verbose_name='Proqrama alınmayan')),
                ('review_operations', models.PositiveIntegerField(default=0, verbose_name='Manual review')),
                ('total_planned_mh', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ümumi plan MH')),
                ('error_message', models.TextField(blank=True, verbose_name='Xəta məlumatı')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlama vaxtı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitmə vaxtı')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_runs', to='planning.weeklyplan', verbose_name='Həftəlik proqram')),
            ],
            options={
                'verbose_name': 'Scheduling Run',
                'verbose_name_plural': 'Scheduling Run-lar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('SCHEDULED', 'Proqrama alındı'), ('NOT_SCHEDULED', 'Proqrama alınmadı'), ('REVIEW', 'Manual yoxlama tələb olunur')], db_index=True, default='REVIEW', max_length=20, verbose_name='Planlama qərarı')),
                ('decision_reason', models.TextField(blank=True, verbose_name='Qərarın səbəbi')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prioritet')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date')),
                ('is_overdue', models.BooleanField(db_index=True, default=False, verbose_name='Gecikmiş iş')),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Planlanan tarix')),
                ('scheduled_start', models.TimeField(blank=True, null=True, verbose_name='Başlama saatı')),
                ('scheduled_end', models.TimeField(blank=True, null=True, verbose_name='Bitmə saatı')),
                ('required_people', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ayrılan adam sayı')),
                ('planned_mh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Planlanan adam-saat')),
                ('planned_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Planlanan müddət, saat')),
                ('sequence', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Planlama ardıcıllığı')),
                ('scheduler_score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Scheduler balı')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Manual kilidlənib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_results', to='planning.sapoperation', verbose_name='SAP Operation')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_operations', to='planning.weeklyplan', verbose_name='Həftəlik proqram')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_operations', to='capacity.workcenter', verbose_name='Planlanan ekip')),
            ],
            options={
                'verbose_name': 'Planlanmış operation',
                'verbose_name_plural': 'Planlanmış operation-lar',
                'ordering': ['scheduled_date', 'scheduled_start', 'sequence'],
                'indexes': [models.Index(fields=['weekly_plan', 'decision'], name='scheduling__weekly__cc3518_idx'), models.Index(fields=['weekly_plan', 'work_center', 'scheduled_date'], name='scheduling__weekly__6ec606_idx')],
                'constraints': [models.UniqueConstraint(fields=('weekly_plan', 'sap_operation'), name='unique_operation_per_week_schedule')],
            },
        ),
    ]
