# Generated by Django 6.1 on 2026-08-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, verbose_name='İş tarixi')),
                ('start_time', models.TimeField(verbose_name='Başlama saatı')),
                ('end_time', models.TimeField(verbose_name='Bitmə saatı')),
                ('required_people', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Adam sayı')),
                ('segment_mh', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Segment MH')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Segment ardıcıllığı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='scheduling.scheduledoperation', verbose_name='Planlanmış operation')),
            ],
            options={
                'verbose_name': 'Schedule segment',
                'verbose_name_plural': 'Schedule segmentləri',
                'ordering': ['work_date', 'start_time', 'sequence'],
                'indexes': [models.Index(fields=['work_date', 'start_time'], name='scheduling__work_da_bd034b_idx')],
            },
        ),
    ]
