# Generated by Django 6.1 on 2026-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_schedulesegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledoperation',
            name='required_people',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tələb olunan adam sayı'),
        ),
        migrations.AlterField(
            model_name='scheduledoperation',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Planlanan başlanğıc tarixi'),
        ),
        migrations.AlterField(
            model_name='scheduledoperation',
            name='scheduled_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Son segmentin bitmə saatı'),
        ),
        migrations.AlterField(
            model_name='schedulingrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Hesablanır'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Xəta')], db_index=True, default='RUNNING', max_length=20, verbose_name='Status'),
        ),
    ]
