# Generated by Django 6.1 on 2026-08-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Ekip kodu')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Ekip adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Ekip',
                'verbose_name_plural': 'Ekiplər',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.PositiveIntegerField(verbose_name='Mövcud adam sayı')),
                ('productive_hours_per_day', models.DecimalField(decimal_places=2, default=6.75, max_digits=4, verbose_name='Gündəlik məhsuldar saat')),
                ('working_days', models.PositiveSmallIntegerField(default=5, verbose_name='İş günü sayı')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='planning.weeklyplan', verbose_name='Həftəlik proqram')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_capacities', to='capacity.workcenter', verbose_name='Ekip')),
            ],
            options={
                'verbose_name': 'Həftəlik kapasite',
                'verbose_name_plural': 'Həftəlik kapasitələr',
                'constraints': [models.UniqueConstraint(fields=('weekly_plan', 'work_center'), name='unique_weekly_workcenter_capacity')],
            },
        ),
    ]
