# Generated by Django 6.1 on 2026-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklycapacity',
            name='unique_weekly_workcenter_capacity',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='name',
        ),
        migrations.AddField(
            model_name='workcenter',
            name='headcount',
            field=models.PositiveIntegerField(default=0, verbose_name='Adam sayı'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='productive_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=6.75, max_digits=4, verbose_name='Məhsuldar saat / gün'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='WorkCenter'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.DeleteModel(
            name='WeeklyCapacity',
        ),
    ]
