# Generated by Django 6.1 on 2026-08-23 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0002_remove_weeklycapacity_unique_weekly_workcenter_capacity_and_more'),
        ('planning', '0002_saporder_sapoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcenter',
            name='headcount',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='productive_hours_per_day',
        ),
        migrations.AddField(
            model_name='workcenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workcenter',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ekip adı'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='WorkCenter'),
        ),
        migrations.CreateModel(
            name='WeeklyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.PositiveIntegerField(verbose_name='Mövcud adam sayı')),
                ('productive_hours_per_day', models.DecimalField(decimal_places=2, default=6.75, max_digits=4, verbose_name='Məhsuldar saat / gün')),
                ('working_days', models.PositiveSmallIntegerField(default=5, verbose_name='İş günü sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_capacities', to='planning.weeklyplan', verbose_name='Həftəlik proqram')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_history', to='capacity.workcenter', verbose_name='WorkCenter')),
            ],
            options={
                'verbose_name': 'Həftəlik kapasite',
                'verbose_name_plural': 'Həftəlik kapasitələr',
                'ordering': ['-weekly_plan__year', '-weekly_plan__week_number', 'work_center__code'],
                'constraints': [models.UniqueConstraint(fields=('weekly_plan', 'work_center'), name='unique_week_workcenter_capacity')],
            },
        ),
    ]
