# Generated by Django 6.1 on 2026-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Proqramın adı')),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='Həftə nömrəsi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='İl')),
                ('start_date', models.DateField(verbose_name='Başlama tarixi')),
                ('end_date', models.DateField(verbose_name='Bitmə tarixi')),
                ('status', models.CharField(choices=[('DRAFT', 'Hazırlanır'), ('SCHEDULED', 'Proqram hazırlanıb'), ('APPROVED', 'Təsdiqlənib'), ('CLOSED', 'Bağlanıb')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-week_number'],
                'constraints': [models.UniqueConstraint(fields=('year', 'week_number'), name='unique_year_week')],
            },
        ),
    ]
