# Generated by Django 6.1 on 2026-08-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Sifariş nömrəsi')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prioritet')),
                ('order_type', models.CharField(blank=True, max_length=20, verbose_name='Sifariş tipi')),
                ('created_on', models.DateField(blank=True, null=True, verbose_name='Yaranma tarixi')),
                ('system_status', models.CharField(blank=True, max_length=255, verbose_name='Sistem statusu')),
                ('revision', models.CharField(blank=True, max_length=50, verbose_name='Revision')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Sistemə yüklənmə vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAP sifarişi',
                'verbose_name_plural': 'SAP sifarişləri',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='SAPOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=20, verbose_name='Operation nömrəsi')),
                ('work_center_code_raw', models.CharField(blank=True, max_length=50, verbose_name='SAP-dakı ekip kodu')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='İşin təsviri')),
                ('required_people', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tələb olunan adam sayı')),
                ('planned_work_mh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Planlanan adam-saat')),
                ('actual_work_mh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Faktiki adam-saat')),
                ('operation_system_status', models.CharField(blank=True, max_length=255, verbose_name='Operation sistem statusu')),
                ('user_status', models.CharField(blank=True, max_length=255, verbose_name='İstifadəçi statusu')),
                ('maintenance_activity_type', models.CharField(blank=True, max_length=50, verbose_name='Təmir fəaliyyət tipi')),
                ('revision', models.CharField(blank=True, max_length=50, verbose_name='Operation Revision')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_operations', to='capacity.workcenter', verbose_name='İcra edən ekip')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='planning.saporder', verbose_name='Sifariş')),
            ],
            options={
                'verbose_name': 'SAP operation',
                'verbose_name_plural': 'SAP operation-ları',
                'ordering': ['order__order_number', 'operation_number'],
                'constraints': [models.UniqueConstraint(fields=('order', 'operation_number'), name='unique_order_operation')],
            },
        ),
    ]
