# Generated by Django 6.1 on 2026-08-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_saporder_sapoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITKRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=30, verbose_name='SAP sifariş nömrəsi')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='İTK qeydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itk_requests', to='planning.weeklyplan', verbose_name='Proqram həftəsi')),
            ],
            options={
                'verbose_name': 'İTK proqram tələbi',
                'verbose_name_plural': 'İTK proqram tələbləri',
                'ordering': ['weekly_plan', 'order_number'],
                'constraints': [models.UniqueConstraint(fields=('weekly_plan', 'order_number'), name='unique_itk_order_per_week')],
            },
        ),
    ]
