# Generated by Django 6.1 on 2026-08-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_itkrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Tarix')),
                ('day_type', models.CharField(choices=[('WORKING', 'İş günü'), ('WEEKEND', 'Həftəsonu'), ('HOLIDAY', 'Rəsmi bayram'), ('NON_WORKING', 'Qeyri-iş günü'), ('SPECIAL_WORKING', 'Xüsusi iş günü')], db_index=True, default='WORKING', max_length=20, verbose_name='Günün tipi')),
                ('is_working_day', models.BooleanField(db_index=True, default=True, verbose_name='İş günüdür')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Günün adı / qeyd')),
                ('working_hours', models.DecimalField(decimal_places=2, default=6.75, max_digits=4, verbose_name='Məhsuldar iş saatı')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Məlumat mənbəyi')),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='Manual dəyişiklik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İş təqvimi günü',
                'verbose_name_plural': 'İş təqvimi günləri',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'is_working_day'], name='planning_wo_date_7b6841_idx')],
            },
        ),
    ]
